Support pagination for resources loading
oat-sa/extension-tao-mediamanager pull request #245
Opened 2020-12-09 20:21 UTC by boajer

2020-12-10 13:30 UTC, gabrielfs7 commented on model/MediaSource.php
> +    public function getDirectory(
@boajer  I wrote some comments here about this: https://github.com/oat-sa/tao-core/pull/2747

We should avoid breaking changes and maybe try more explanatory names for parameters. Can you take a look please? Wdyt?

2020-12-10 13:48 UTC, shpran approved these changes
LGTM 👍🏻 
Some cs comments :)

- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2020-12-10 13:48 UTC, shpran commented on model/MediaSource.php
>      {
[PSR-12](https://www.php-fig.org/psr/psr-2/#44-method-arguments): `When the argument list is split across multiple lines, the closing parenthesis and opening brace MUST be placed together on their own line with one space between them.`
```suggestion
    ): array {
```

2020-12-10 13:48 UTC, shpran commented on model/MediaSource.php
> +            $options = array_filter($options);
```suggestion
            $options = array_filter([
                'limit' => $limit,
                'offset' => $offset,
            ]);
```

2020-12-15 08:36 UTC, mike-ionut-mihai-sandu-tao reviewed
lgtm ,  just a few comments

2020-12-15 08:36 UTC, mike-ionut-mihai-sandu-tao commented on model/MediaSource.php
> +        return $this->searchDirectories($params->getParentLink(), $params->getFilter(), $params->getDepth(),
as a future improvement let's format the code as per our team agreement 
if the elements are not fitting then
 - one
 - under the other

2020-12-15 08:36 UTC, mike-ionut-mihai-sandu-tao commented on model/MediaSource.php
> +    private function searchDirectories(
think you need to update the test:: MediaSourceTest

2020-12-15 09:29 UTC, bartlomiejmarszal requested changes
You added `getDirectories` method. I think you need new test for this.

2020-12-15 09:29 UTC, bartlomiejmarszal commented on model/MediaSource.php
> +        return $this->searchDirectories($params->getParentLink(), $params->getFilter(), $params->getDepth(),
Let's do this in this PR

2020-12-15 09:50 UTC, gabrielfs7 commented on model/MediaSource.php
> +    public function getDirectories(QueryObject $params): array
I have some suggestions. 

1) This will be an object by nature, so no need to write object in the name `QueryObject` => `DirectorySearchQuery`.
2) This object does not belong to media manager, since it can be used to search directories in other implementations (I would move it to tao-core where the `MediaBrowser` is)

Wdyt?

2020-12-15 09:52 UTC, gabrielfs7 commented on model/MediaSource.php
> +                    $this->logEmergency($e->getMessage());
Do you think is good to provide extra info in the log that can help detect the issue, like the `$instance->getUri()`?

2020-12-15 09:55 UTC, gabrielfs7 commented on model/MediaSource.php
> +        }
```suggestion
        $class = $this->getClass($parentLink == '' ? $this->getRootClassUri() : tao_helpers_Uri::decode($parentLink));
```
Cleaning suggestion

2020-12-15 09:55 UTC, gabrielfs7 commented on model/MediaSource.php
> +        return $data;
```suggestion
        }
        
        return $data;
```

2020-12-15 10:03 UTC, gabrielfs7 commented
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2020-12-15 12:02 UTC, gabrielfs7 commented on model/MediaSource.php
> +    public function getDirectories(QueryObject $params): array
I just notice this object is in the media manager, so do not consider the 2nd point :)

2020-12-16 14:37 UTC, shpran approved these changes
👍🏻 
Small cs comments

- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2020-12-16 14:37 UTC, shpran commented on model/MediaSource.php
> +
```suggestion
```

2020-12-16 14:37 UTC, shpran commented on model/MediaSource.php
> +                    $childrenOffset);
```suggestion
                    $childrenOffset
                );
```

2020-12-16 14:37 UTC, shpran commented on model/MediaSource.php
> +                    );
```suggestion
                    $this->logEmergency(sprintf(
                        'Encountered issues "%s" while fetching details for %s',
                        $e->getMessage(),
                        $instance->getUri())
                    );
```

2020-12-16 14:49 UTC, gabrielfs7 commented on model/MediaSource.php
> +                    );
By reading it seems `$e->getMessage()` and `$instance->getUri()` are parameters of `logEmergency`, but they are not. It is just to bring some comfort reading and more cohesion in the indentation. What do you think? 

```suggestion
                    $this->logEmergency(
                        sprintf(
                            'Encountered issues "%s" while fetching details for %s',
                            $e->getMessage(),
                            $instance->getUri()
                        )
                    );
```

2020-12-16 14:50 UTC, gabrielfs7 approved these changes
Waiting for final demo! Good job!

2020-12-16 14:55 UTC, mike-ionut-mihai-sandu-tao reviewed
lgtm , 
please apply PSR-12 to your new code and update the tests

2020-12-16 15:19 UTC, bartlomiejmarszal approved these changes
LGTM. 

- [x] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2020-12-17 12:17 UTC, merged