Feature/con 271/store css within passages - draft
oat-sa/extension-tao-mediamanager pull request #250
Opened 2021-01-25 16:32 UTC by pnal

2021-02-09 08:33 UTC, gabrielfs7 commented on model/MediaService.php
> +        }
```suggestion
        if ($directory !== '.') {
            return $this->getFileManager()->deleteDirectory($directory);
        }
        
        return $this->getFileManager()->deleteFile($link);
```

You can avoid else always. It is never required. There are tons of benefits, but is mainly reduces code complexity, increases readability and helps with methods extraction :) 

https://beberlei.de/2020/02/25/clean_code_object_calisthenics_rules_i_try_to_follow.html
https://williamdurand.fr/2013/06/03/object-calisthenics/#2-dont-use-the-else-keyword

2021-02-09 08:44 UTC, gabrielfs7 commented on model/MediaService.php
> +     * @param bool $storeFile
We should always avoid flag methods on public interface. It is not a good practice. For internal private method it is "oksh".

https://martinfowler.com/bliki/FlagArgument.html

We can have 2 separate methods and method content can be splited with better readability. Wdyt?

2021-02-09 08:48 UTC, gabrielfs7 commented on model/SharedStimulusPackageImporter.php
> +        array $cssFiles,
It is a protected method. Are you sure changing the signature is not affecting other places? (If not, maybe convert this method to private?) 

Also. Instead of `cssFiles`, maybe it could be `assets` and we can be prepared for other `attachments` in the future? (like we have for items?)

@pnal wdyt?

2021-02-09 08:52 UTC, gabrielfs7 commented on model/fileManagement/FlySystemManagement.php
> +    public function storeSharedStimulusDirectory($stimulusXmlSource, $stimulusLabel, $stimulusFilename, $cssFiles, $CSSFolderName)
Should not this be in a separate service that uses this class as dependency? Now we are introducing specific QTI naming inside flysystem. Wdyt?

In addition we should add `type hint` and `return type` for the params and response :)

2021-02-09 08:53 UTC, gabrielfs7 commented on model/fileManagement/FlySystemManagement.php
> +    protected function getUniqueFilename($fileName, $keepExtension = true)
Please avoid flag arguments, this leads to dangerous side effects and increase of maintainability issues.

2021-02-09 08:57 UTC, gabrielfs7 commented on model/SharedStimulusPackageImporter.php
> +            helpers_TimeOutHelper::setTimeOutLimit(helpers_TimeOutHelper::LONG);
You are repeating it 2 times. Seems we need either a separate service or a private method. Wdyt?

2021-02-09 10:07 UTC, mike-ionut-mihai-sandu-tao reviewed
left some comments

2021-02-09 10:07 UTC, mike-ionut-mihai-sandu-tao commented on model/SharedStimulusPackageImporter.php
> +                if (preg_match('/^[\w]/', $file->getFilename()) === 1 && $file->getExtension() === 'css') {
could we get this info from the metaData of the file? so we don't need to use preg_match?

2021-02-09 10:07 UTC, mike-ionut-mihai-sandu-tao commented on model/SharedStimulusPackageImporter.php
> +    ): Report {
may i ask you to check your code using the phpcs --standard=PSR12

2021-02-09 10:07 UTC, mike-ionut-mihai-sandu-tao commented on model/ZipExporter.php
> - * Copyright (c) 2014-2020 (original work) Open Assessment Technologies SA;
i would actually go for `2014-2021`

2021-02-09 10:07 UTC, mike-ionut-mihai-sandu-tao commented on model/export/service/SharedStimulusCSSExporter.php
> +        $fs = $this->getFileManagement();
your comment has `$fsManager`
but the name of your variable is $fs
may i ask you to change this for consistency ?

2021-02-09 10:07 UTC, mike-ionut-mihai-sandu-tao commented on model/export/service/SharedStimulusCSSExporter.php
> +        $cssPath = dirname($link) . DIRECTORY_SEPARATOR . self::CSS_DIR_NAME;
maybe we can use flysystem abstraction so we don't depend on local file system?

2021-02-09 10:07 UTC, mike-ionut-mihai-sandu-tao commented on model/fileManagement/FlySystemManagement.php
> +    public function storeSharedStimulusDirectory($stimulusXmlSource, $stimulusLabel, $stimulusFilename, $cssFiles, $CSSFolderName)
maybe $CSSFolderName is not the best name :)

2021-02-09 10:07 UTC, mike-ionut-mihai-sandu-tao commented on model/fileManagement/FlySystemManagement.php
> +            $ext = @pathinfo($fileName, PATHINFO_EXTENSION);
could this break or create side effects if the destination is a AWS or GCP bucket ?

2021-02-09 10:42 UTC, boajer commented on model/SharedStimulusPackageImporter.php
> +            helpers_TimeOutHelper::setTimeOutLimit(helpers_TimeOutHelper::LONG);
Why timeouts become an issue? 
Generally import\export supposed to be executed in `worker` process

2021-02-09 10:44 UTC, boajer commented on model/SharedStimulusPackageImporter.php
> +            // Todo: store related CSS somehow
Would it be part of scope of current PR ?

2021-02-09 10:46 UTC, boajer commented on model/SharedStimulusPackageImporter.php
> +        $CssFileInfoArray = [];
```suggestion
        $cssFileInfoArray = [];
```

2021-02-09 10:47 UTC, boajer commented on model/SharedStimulusPackageImporter.php
> +     * @param Resource $class
We may drop such kind of php doc, by squad convention, whenever it doesn't add extra information on top of type hinting

2021-02-09 10:48 UTC, pnal commented on model/SharedStimulusPackageImporter.php
> +            helpers_TimeOutHelper::setTimeOutLimit(helpers_TimeOutHelper::LONG);
It is not my changes, I just moved this code to the different place

2021-02-09 11:01 UTC, pnal commented on model/SharedStimulusPackageImporter.php
> +            helpers_TimeOutHelper::setTimeOutLimit(helpers_TimeOutHelper::LONG);
May I ask why it needed and can we just remove it?

2021-02-09 12:14 UTC, pnal commented on model/SharedStimulusPackageImporter.php
> +    ): Report {
![image](https://user-images.githubusercontent.com/18700632/107362103-5fac8c80-6ae9-11eb-9d4a-267e605d8dfc.png)
@mike-ionut-mihai-sandu-tao I don't see a problem here

2021-02-09 14:53 UTC, pnal commented on model/SharedStimulusPackageImporter.php
> +        // Todo: find and validate CSS file from zip
removed

2021-02-09 14:53 UTC, pnal commented on model/SharedStimulusPackageImporter.php
> +    private function getSharedStimulusStylesheets($extractPath): ?array
actually this is string

2021-02-09 14:56 UTC, pnal commented on model/SharedStimulusPackageImporter.php
> +                if (preg_match('/^[\w]/', $file->getFilename()) === 1 && $file->getExtension() === 'css') {
Here we use preg_match for filename, not for extension.
We already use same condition for stimulus xml filename, so I kept the same here

2021-02-09 14:58 UTC, pnal commented on model/ZipExporter.php
> - * Copyright (c) 2014-2020 (original work) Open Assessment Technologies SA;
done

2021-02-09 14:58 UTC, pnal commented on model/export/service/SharedStimulusCSSExporter.php
> +        $fs = $this->getFileManagement();
fixed

2021-02-09 14:59 UTC, pnal commented on model/SharedStimulusPackageImporter.php
> +            // Todo: store related CSS somehow
removed todo as not actual

2021-02-09 15:00 UTC, pnal commented on model/SharedStimulusPackageImporter.php
> +        $CssFileInfoArray = [];
fixed

2021-02-09 15:00 UTC, pnal commented on model/SharedStimulusPackageImporter.php
> +     * @param Resource $class
removed @param descriptions

2021-02-09 15:03 UTC, pnal commented on model/fileManagement/FlySystemManagement.php
> +    public function storeSharedStimulusDirectory($stimulusXmlSource, $stimulusLabel, $stimulusFilename, $cssFiles, $CSSFolderName)
fixed

2021-02-09 15:12 UTC, pnal commented on model/fileManagement/FlySystemManagement.php
> +    public function storeSharedStimulusDirectory($stimulusXmlSource, $stimulusLabel, $stimulusFilename, $cssFiles, $CSSFolderName)
Thanks, agree
created separate service

2021-02-09 15:13 UTC, pnal commented on model/fileManagement/FlySystemManagement.php
> +    protected function getUniqueFilename($fileName, $keepExtension = true)
the method cloned to separate service, removed flag from this one

2021-02-09 15:18 UTC, pnal commented on model/SharedStimulusPackageImporter.php
> +            helpers_TimeOutHelper::setTimeOutLimit(helpers_TimeOutHelper::LONG);
@gabrielfs7 It has been moved outside from getSharedStimulusFile as is.
I'm not sure if this is still needed. So did not refactor.

2021-02-09 15:28 UTC, pnal commented on model/SharedStimulusPackageImporter.php
> +        array $cssFiles,
- I don't see any reason why it is protected. Did not found any outside usage.
- We already store assets two different ways (base64 + media relations) and this is a bit confusing. For the moment we do not know how it will be changed in future so I consider do not try to predict and leave any misleading mentions in the code.

2021-02-09 16:17 UTC, pnal commented on model/MediaService.php
> +        $directory = dirname($link);
@mike-ionut-mihai-sandu-tao @boajer it just needed to determine if the link points to the file in the root or a file inside a sub-directory
the link goes from the DB:
![image](https://user-images.githubusercontent.com/18700632/107392686-fccbed00-6b0a-11eb-9792-088fcfb0078c.png)
and dirname function actually do not get any file just helps to get a parent directory name of the file in the path string

2021-02-10 08:18 UTC, pnal commented on model/SharedStimulusPackageImporter.php
> +            helpers_TimeOutHelper::setTimeOutLimit(helpers_TimeOutHelper::LONG);
removed to zipImporter

2021-02-10 08:19 UTC, pnal commented on model/SharedStimulusPackageImporter.php
> +            helpers_TimeOutHelper::setTimeOutLimit(helpers_TimeOutHelper::LONG);
refactored

2021-02-10 08:19 UTC, pnal commented on model/SharedStimulusPackageImporter.php
> +            helpers_TimeOutHelper::setTimeOutLimit(helpers_TimeOutHelper::LONG);
refactored

2021-02-10 14:12 UTC, mike-ionut-mihai-sandu-tao reviewed
good job , left some comments

2021-02-10 14:12 UTC, mike-ionut-mihai-sandu-tao commented on model/MediaService.php
> +        // @todo: move taoRevision stuff under a listener of MediaSavedEvent
we have a left todo >  either fix it or remove it please

2021-02-10 14:12 UTC, mike-ionut-mihai-sandu-tao commented on model/MediaService.php
> +        $md5 = md5($content);
maybe we can move this at line 163 directly because i see no other usage

2021-02-10 14:12 UTC, mike-ionut-mihai-sandu-tao commented on model/MediaService.php
> +    public function createSharedStimulusInstance(
please format this using phpcs --standard=PSR12

2021-02-10 14:12 UTC, mike-ionut-mihai-sandu-tao commented on model/MediaService.php
> +        $directory = dirname($link);
makes sense

2021-02-10 14:12 UTC, mike-ionut-mihai-sandu-tao commented on model/SharedStimulusPackageImporter.php
> +     * @throws common_Exception if the xml not found
leftover comment , let's remove please

2021-02-10 14:12 UTC, mike-ionut-mihai-sandu-tao commented on model/SharedStimulusPackageImporter.php
> +    private function getSharedStimulusStylesheets($extractPath): ?array
let put string then if possible :) , i misread the code from my side

2021-02-10 14:12 UTC, mike-ionut-mihai-sandu-tao commented on model/export/service/SharedStimulusCSSExporter.php
> +        // Check CSS has valid structure and classes (in scope of future tasks)
not required

2021-02-10 14:12 UTC, mike-ionut-mihai-sandu-tao commented on model/sharedStimulus/service/StoreService.php
> +
extra lines

2021-02-10 14:12 UTC, mike-ionut-mihai-sandu-tao commented on model/sharedStimulus/service/StoreService.php
> +    public function store($stimulusXmlSource, $stimulusFilename, $cssFiles): string
i think we are missing some tests

2021-02-10 14:12 UTC, mike-ionut-mihai-sandu-tao commented on model/fileManagement/FlySystemManagement.php
> +    public function writeStream($path, $resource, array $config = []): bool
why? 
you have storeFile
also for the other you have getFilesystem that will return you 
\oat\oatbox\filesystem\FileSystemService
and that has already what you need

2021-02-10 14:28 UTC, boajer commented on model/SharedStimulusPackageImporter.php
> +    private function getSharedStimulusFile($extractPath): string
```suggestion
    private function getSharedStimulusFile(string $extractPath): string
```

2021-02-10 14:36 UTC, pnal commented on model/fileManagement/FlySystemManagement.php
> +    public function writeStream($path, $resource, array $config = []): bool
@mike-ionut-mihai-sandu-tao 
`storeFile` does not fit, it creates filename by itself
`getFilesystem` is protected

2021-02-11 15:47 UTC, pnal commented on model/sharedStimulus/service/StoreService.php
> +    public function store($stimulusXmlSource, $stimulusFilename, $cssFiles): string
Right now there is nothing to test, just simple logic and concatenations, even so I created one unit test for this service

2021-02-12 07:29 UTC, gabrielfs7 commented on test/integration/model/SharedStimulusPackageImporterTest.php
> +    private $storeServiceMock = null;
Please, do not use `= null`, cause it is redundant.
Also add phpdoc with class type.

2021-02-12 07:31 UTC, gabrielfs7 commented on model/MediaService.php
> +     * @return string | bool $instanceUri or false on error
Can we work with exceptions, please? The multitype return is legacy of ancient PHP that did not have exceptions. Also we should have strict return types and type hints.

2021-02-12 07:31 UTC, gabrielfs7 commented on model/MediaService.php
> +     * Create a shared stimulus media instance from a file, and define its class and language
We do not document what method is doing. The method name and namespace context should be self-explanatory.

2021-02-12 07:33 UTC, gabrielfs7 commented on model/SharedStimulusPackageImporter.php
> +    private function getSharedStimulusStylesheets($extractPath): ?array
@pnal The return is never null, please fix the return type to `array`.

2021-02-12 07:36 UTC, gabrielfs7 commented on model/export/service/SharedStimulusCSSExporter.php
> +     * stylesheets folder name inside zip archive
Do we need to document this?

2021-02-12 07:42 UTC, gabrielfs7 commented on test/integration/model/SharedStimulusPackageImporterTest.php
> +    private $storeServiceMock = null;
You can refer to https://oat-sa.atlassian.net/wiki/spaces/NEX/pages/311492833/CR+guidelines+for+Construct. Here you have all standards to follow (not just PSR-12)

2021-02-12 07:44 UTC, gabrielfs7 commented on model/sharedStimulus/service/StoreService.php
> +    public function store($stimulusXmlSource, $stimulusFilename, $cssFiles): string
We are missing type hints too. And we can also remove the annotations.

2021-02-12 07:48 UTC, gabrielfs7 commented on model/fileManagement/FlySystemManagement.php
> +    public function writeStream($path, $resource, array $config = []): bool
On top of that, we are not following the interface `oat\taoMediaManager\model\fileManagement\FileManagement`, so the places relying on this interface are not supposed to work with this. I would remove those new public methods and use the file `getFileSystem` directly on those places. It is breaking open/closed principle.

2021-02-15 08:20 UTC, bartlomiejmarszal requested changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2021-02-15 08:20 UTC, bartlomiejmarszal commented on model/SharedStimulusPackageImporter.php
> + * Copyright (c) 2021 (original work) Open Assessment Technologies SA;
```suggestion
 * Copyright (c) 2014-2021 (original work) Open Assessment Technologies SA;
```

2021-02-15 09:19 UTC, pnal commented on model/fileManagement/FlySystemManagement.php
> +    public function writeStream($path, $resource, array $config = []): bool
Thanks, I agree, removed those methods

2021-02-15 09:37 UTC, pnal commented on model/MediaService.php
> + * Copyright (c) 2021 (original work) Open Assessment Technologies SA;
Thanks, fixed

2021-02-15 09:37 UTC, pnal commented on model/SharedStimulusPackageImporter.php
> + * Copyright (c) 2021 (original work) Open Assessment Technologies SA;
Thanks, fixed

2021-02-16 09:39 UTC, gabrielfs7 commented on model/SharedStimulusPackageImporter.php
> +                if (preg_match('/^[\w]/', $file->getFilename()) === 1 && $file->getExtension() === 'css') {
@pnal Then we should at least have a private method to check this instead of repeat the code https://github.com/oat-sa/extension-tao-mediamanager/pull/250/files#diff-a1d8cae2945dac748ac689dd2b94bad9caff9d64712ffb4d53e8e0a0dfccae13R216


```
private function isFileExtension(SplFileInfo $file, string $extension)
{
    if ($file->isFile()) {
        return preg_match('/^[\w]/', $file->getFilename()) === 1 && $file->getExtension() === $extension;
    }

    return false;
}
```

Then you can use it on both iterators

2021-02-16 09:43 UTC, gabrielfs7 commented on model/sharedStimulus/service/StoreService.php
> +    public const CSS_DIR_NAME = 'CSS';
We do not use upper case for directories. It might cause issues. Lets use lower case instead. 

This is repeated from here too. Could we unify the place where this info is stored? 

https://github.com/oat-sa/extension-tao-mediamanager/pull/250/files#diff-3e33bd013af37f8aa0a2b9950c8ad9aa120c5a8f3b37e575fce142f2707c9c18R36

2021-02-16 09:44 UTC, gabrielfs7 commented on test/integration/model/SharedStimulusPackageImporterTest.php
> +    private $storeServiceMock;
Blank lines required according to our code guideline

```suggestion
    private $mediaServiceMock;
    
    /* @var StoreService|MockObject */
    
    private $storeServiceMock;
```

2021-02-16 09:45 UTC, gabrielfs7 commented on test/unit/model/sharedStimulus/service/StoreServiceTest.php
> +    private function getPreparedServiceInstance($fileSystemMock)
In php 7 we have the return types, so we should use. Even if this is a mock, the return type is still `StoreService`.

```suggestion
    private function getPreparedServiceInstance($fileSystemMock): StoreService
```

2021-02-16 09:46 UTC, gabrielfs7 commented on test/unit/model/sharedStimulus/service/StoreServiceTest.php
> +    private function initFileSystemMock()
Same as here: https://github.com/oat-sa/extension-tao-mediamanager/pull/250/files#r576684909

2021-02-16 12:43 UTC, pnal commented on model/sharedStimulus/service/StoreService.php
> +    public const CSS_DIR_NAME = 'CSS';
@gabrielfs7 First point makes sense I will change to lower case.
Those constants are different and logically do not depend on each other:
- one is the name of sub directory to store data
- second is the name of directory inside the exported archive

2021-02-16 12:46 UTC, gabrielfs7 commented on model/sharedStimulus/service/StoreService.php
> +    public const CSS_DIR_NAME = 'CSS';
But they should be **always** the same, no? The customer does not chose to put this file on any other path and IMO it is better to keep both consistent. If you keep to constants, this encourages us to use different structure.

2021-02-17 12:19 UTC, pnal commented on model/sharedStimulus/service/StoreService.php
> +    public const CSS_DIR_NAME = 'CSS';
@gabrielfs7 Why? What would you say if I already gave them different names?
I agree that we don't have any AC for that names right now.
But first one is for storage structure, and the second is for a specific functionality (export zipped package). I have concerns that if we unify them and put in one place it will encourage us to proceed like that they are one and the same.

2021-02-17 13:50 UTC, pnal commented on model/SharedStimulusPackageImporter.php
> +                if (preg_match('/^[\w]/', $file->getFilename()) === 1 && $file->getExtension() === 'css') {
@gabrielfs7 totally agree, thanks

2021-02-18 08:37 UTC, mike-ionut-mihai-sandu-tao approved these changes
lgtm
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2021-02-18 09:21 UTC, gabrielfs7 reviewed
Good job!

Code ok. Did not test it locally, only saw the demo. Please fix tests and resolve the conflicts

- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2021-02-18 09:38 UTC, gabrielfs7 approved these changes

2021-02-18 09:40 UTC, pnal commented on model/MediaService.php
> +        $userId = null
fixed

2021-02-18 09:41 UTC, pnal commented on model/SharedStimulusPackageImporter.php
> +    private function getSharedStimulusStylesheets($extractPath): ?array
fixed

2021-02-19 09:00 UTC, bartlomiejmarszal requested changes
Missing test for SharedStimulusCSSExporter

2021-02-19 09:18 UTC, bartlomiejmarszal reviewed
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2021-02-20 12:10 UTC, pnal commented
> Missing test for SharedStimulusCSSExporter

Test added

2021-02-24 09:16 UTC, bartlomiejmarszal reviewed
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2021-02-24 09:17 UTC, bartlomiejmarszal approved these changes
LGTM

2021-02-25 15:25 UTC, merged