Feature/AUT-18/Style editor - text block in passage
oat-sa/extension-tao-mediamanager pull request #262
Opened 2021-03-17 13:11 UTC by bziondik

2021-03-19 10:15 UTC, AnastasiaArcadia commented on views/js/qtiCreator/component/tpl/sharedStimulusAuthoring.tpl
> +                                              data-target="body .hashClass" data-additional="padding:20px"></span>
What is `data-additional` attribute used for, can't we use standard css?

2021-03-19 10:47 UTC, ampaveliev commented on views/js/qtiCreator/editor/styleEditor/fontSizeChanger.js
> +            .on('click', function (e) {
Sometimes `NaN` appears in the input. To reproduce, you need to click the reset button and then try to increase / decrease size via buttons

2021-03-19 10:55 UTC, ampaveliev commented on views/js/qtiCreator/component/tpl/sharedStimulusAuthoring.tpl
> +                                        <span class="icon-eraser reset-button" data-value="background-color"
Can be input type color be used here? If not, can clickable spans be replaced with the buttons for a11y reasons? Also, I'd recommend wrapping buttons into labels. In this case, we don't need to create ids. If it is not possible, I think we should use more specific ids.

2021-03-19 10:57 UTC, ampaveliev commented on views/js/qtiCreator/component/tpl/sharedStimulusAuthoring.tpl
> +                                            <a href="#" data-action="reduce" title="{{__ 'Reduce font size'}}"
Buttons are better for a11y reasons.

2021-03-19 11:00 UTC, ampaveliev requested changes
Works great. However, I have some comments

2021-03-22 15:09 UTC, bziondik commented on views/js/qtiCreator/component/tpl/sharedStimulusAuthoring.tpl
> +                                        <span class="icon-eraser reset-button" data-value="background-color"
input type color is not supported in IE https://caniuse.com/input-color

2021-03-22 15:09 UTC, bziondik commented on views/js/qtiCreator/editor/styleEditor/fontSizeChanger.js
> +            .on('click', function (e) {
Thanks! will fix

2021-03-22 15:10 UTC, bziondik commented on views/js/qtiCreator/component/tpl/sharedStimulusAuthoring.tpl
> +                                              data-target="body .hashClass" data-additional="padding:20px"></span>
This is additional styles that should be added if property is set.

2021-03-22 15:14 UTC, bziondik commented on views/js/qtiCreator/component/tpl/sharedStimulusAuthoring.tpl
> +                                            <a href="#" data-action="reduce" title="{{__ 'Reduce font size'}}"
We have a lot of problems with a11y in Authoring, it can be done in separate task

2021-03-22 16:01 UTC, bziondik commented on views/js/qtiCreator/editor/styleEditor/fontSizeChanger.js
> +            .on('click', function (e) {
Fixed

2021-03-22 17:46 UTC, AnastasiaArcadia approved these changes
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not master

2021-03-23 07:25 UTC, ampaveliev commented on views/js/qtiCreator/component/tpl/sharedStimulusAuthoring.tpl
> +                                            <a href="#" data-action="reduce" title="{{__ 'Reduce font size'}}"
It sounds like a broken window: if we have a broken window in our district, we'll build new houses with such flaws. If we can essentially improve our code quality without significant effort, why should we avoid it? So could you please replace new spans with buttons?

2021-03-23 07:29 UTC, ampaveliev commented on views/js/qtiCreator/editor/styleEditor/fontSizeChanger.js
> +            .on('click', function (e) {
I found another way to reproduce NaN. Users can type non-numeric value and then press + or - buttons. But not sure if it should be fixed

2021-03-23 08:39 UTC, bziondik commented on views/js/qtiCreator/component/tpl/sharedStimulusAuthoring.tpl
> +                                            <a href="#" data-action="reduce" title="{{__ 'Reduce font size'}}"
Fixed

2021-03-23 11:41 UTC, bziondik commented on views/js/qtiCreator/editor/styleEditor/fontSizeChanger.js
> +            .on('click', function (e) {
Fixed

2021-03-23 11:56 UTC, ampaveliev approved these changes
Works like a charm

- [ ]  New code is covered by tests (if applicable)
- [x]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [ ]  New code is respecting best practices
- [ ]  Feature is working correctly on my local machine (if applicable)
- [ ]  Acceptance criteria are respected
- [ ]  Pull request title and description are meaningful
- [ ]  Pull request's target is not master

2021-03-25 11:33 UTC, merged