Feature/AUT-35/Adding rich passages styling to an item
oat-sa/extension-tao-mediamanager pull request #274
Opened 2021-05-19 23:47 UTC by shpran

## Relates to: _[AUT-35](https://oat-sa.atlassian.net/browse/AUT-35)_

### Changes
* Added an endpoint to get the stylesheet list for the necessary passage;
* Added an endpoint to get the stylesheet for the necessary passage;
* Code refactoring.

### How to test
1. Create a passage;
2. Style this passage and save;
3. Go to `[[ HOST ]]/taoMediaManager/SharedStimulusStyling/getStylesheets?uri=[[ PASSAGE_URI ]]` and check response - it should contain a list of related stylesheet files (names only);
4. Go to `[[ HOST ]]/taoMediaManager/SharedStimulusStyling/loadStylesheet?uri=[[ PASSAGE_URI ]]&stylesheet=[[ STYLESHEET_NAME ]]` and check response - it should contain a css content (`text/css`).

2021-05-20 11:48 UTC, mike-ionut-mihai-sandu-tao reviewed
left some comments , 
i think we require a bit of refactoring but overall it does not look bad

2021-05-20 11:48 UTC, mike-ionut-mihai-sandu-tao commented on controller/SharedStimulusStyling.php
> +    public function save(
this is a big change in the contract from 0 prams to 3 mandatory ones 
are you sure this will not impact some other flows ?

2021-05-20 11:48 UTC, mike-ionut-mihai-sandu-tao commented on controller/SharedStimulusStyling.php
> +    public function load(
same here : 
this is a big change in the contract from 0 prams to 3 mandatory ones
are you sure this will not impact some other flows ?

2021-05-20 11:48 UTC, mike-ionut-mihai-sandu-tao commented on controller/SharedStimulusStyling.php
> +    public function getStylesheets(
i think we should put this into some getters and provide a default object init as this is being repeated too many times

2021-05-20 11:48 UTC, mike-ionut-mihai-sandu-tao commented on controller/SharedStimulusStyling.php
> +        ResponseFormatter $responseFormatter,
yes after the 4th time reading the same change i believe that this should be seamless injected by constructor or by getting them from 1 or more getters

2021-05-20 11:48 UTC, mike-ionut-mihai-sandu-tao commented on model/sharedStimulus/css/CommandInterface.php
> +interface CommandInterface
the name CommandInterface with getUri does not click for me

2021-05-20 11:48 UTC, mike-ionut-mihai-sandu-tao commented on model/sharedStimulus/css/service/LoadService.php
> +            Logger::d(
if we have that abstract ConfigurableCssService can we inject please the Logger by using the loggerawaretrait and remove this static call please

2021-05-20 11:48 UTC, mike-ionut-mihai-sandu-tao commented on model/sharedStimulus/css/service/LoadService.php
> +                    'Stylesheet %s does not exist yet, returning empty array',
the message looks good but does not provide any information on what is actually happening , so if you can find a better wording that would be highly appreciated

2021-05-20 14:42 UTC, shpran commented on controller/SharedStimulusStyling.php
> +        ResponseFormatter $responseFormatter,
To pass them to `__construct` we should use `InjectionAwareService` instead of `tao_actions_CommonModule`
In this case we will have the possibility to do this:
```
private $service1;
private $service2;

public function __construct(Service1 $service1, Service2 $service2)
{
    $this->service1 = $service1;
    $this->service2 = $service2;
}
```
And everything will work. But in this case our controller becomes a service and I don't think that we need this.

---

In case, if we don't want to use `InjectionAwareService` and want to use `tao_actions_CommonModule` we cannot use `$this->getServiceLocator()` inside `__construct` (will return `null`).
\+ I don't think we need to pass services as class properties in case we use this properties one time per request, they will not be reused by other controller method.

---

Then we will back to previous solution with multiple getters:
```
public function getService1(): Service1
{
    return $this->getServiceLocator()->get(Service1::class);
}

public function getService2(): Service2
{
    return $this->getServiceLocator()->get(Service2::class);
}
```

But I don't like this approach, because previously we added comfortable feature, which allow us to provide Services directly into method and they will be automatically injected.
As I know, @SergiiTao was added this feature (please, confirm if I'm right)

2021-05-20 14:52 UTC, shpran commented on model/sharedStimulus/css/CommandInterface.php
> +interface CommandInterface
Maybe `ResourceUriInterface` ? Wdyt @mike-ionut-mihai-sandu-tao

2021-05-20 15:22 UTC, mike-ionut-mihai-sandu-tao approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2021-05-21 07:19 UTC, bartlomiejmarszal requested changes
There is no unit tests

- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2021-05-21 07:37 UTC, bartlomiejmarszal requested changes
I recommend refactoring few of your classes. I'm also concerned that you change few of classes methods making braking change here.

2021-05-21 07:37 UTC, bartlomiejmarszal commented on model/sharedStimulus/css/GetStylesheetsResourceUri.php
> +class GetStylesheetsResourceUri implements ResourceUriInterface
This name looks like method name not a class name

2021-05-21 07:37 UTC, bartlomiejmarszal commented on model/sharedStimulus/css/GetStylesheetsResourceUri.php
> +class GetStylesheetsResourceUri implements ResourceUriInterface
```suggestion
class StylesheetResourceUri implements ResourceUriInterface
```
Stylesheets? - > stylesheet?

2021-05-21 07:37 UTC, bartlomiejmarszal commented on model/sharedStimulus/css/LoadResourceUri.php
> -class LoadCommand
What happen to this class? Is no longer needed?  Shouldn't we deprecated it and create new one instead renaming?

2021-05-21 07:37 UTC, bartlomiejmarszal commented on model/sharedStimulus/css/LoadStylesheetResourceUri.php
> +class LoadStylesheetResourceUri implements ResourceUriInterface
They have this same interface yet it has one more method?

2021-05-21 07:37 UTC, bartlomiejmarszal commented on model/sharedStimulus/css/factory/CommandFactory.php
> -    public function makeSaveCommandByRequest(ServerRequestInterface $request): SaveCommand
We are modifying  existing public method, is this a braking change?

2021-05-21 07:37 UTC, bartlomiejmarszal commented on model/sharedStimulus/css/factory/CommandFactory.php
> -    public function makeLoadCommandByRequest(ServerRequestInterface $request): LoadCommand
We are modifying existing public method, is this a braking change?

2021-05-21 07:37 UTC, bartlomiejmarszal commented on model/sharedStimulus/css/factory/CommandFactory.php
> +    public function makeGetStylesheetsCommandByRequest(ServerRequestInterface $request): GetStylesheetsResourceUri
```suggestion
    public function executeGetStylesheetsCommandByRequest(ServerRequestInterface $request): GetStylesheetsResourceUri
```

2021-05-21 07:37 UTC, bartlomiejmarszal commented on model/sharedStimulus/css/factory/CommandFactory.php
> +    public function makeLoadStylesheetCommandByRequest(ServerRequestInterface $request): LoadStylesheetResourceUri
```suggestion
    public function executeLoadStylesheetCommandByRequest(ServerRequestInterface $request): LoadStylesheetResourceUri
```

2021-05-21 07:40 UTC, shpran commented on model/sharedStimulus/css/GetStylesheetsResourceUri.php
> +class GetStylesheetsResourceUri implements ResourceUriInterface
I deployed this by mistake: when I renamed `CommandInterface` to `ResourceUriInterface` - PhpStorm renamed these 4 classes. Will fix it, thanks!

2021-05-21 07:49 UTC, shpran commented on model/sharedStimulus/css/LoadResourceUri.php
> -class LoadCommand
Fixed, renamed by mistake, thanks

2021-05-21 07:50 UTC, shpran commented on model/sharedStimulus/css/LoadStylesheetResourceUri.php
> +class LoadStylesheetResourceUri implements ResourceUriInterface
Class name was wrong (fixed).
This interface used for [this method](https://github.com/oat-sa/extension-tao-mediamanager/pull/274/files#diff-2e50f291c98ce393c3afa8db49dc4b1723714124aa26fc3dd38dd62db861f624R36) to get path by uri

2021-05-21 07:52 UTC, shpran commented on model/sharedStimulus/css/factory/CommandFactory.php
> +    public function makeGetStylesheetsCommandByRequest(ServerRequestInterface $request): GetStylesheetsResourceUri
This method creates a new instance of `GetStylesheetsCommand` and returns it.
We do not execute anything here.

2021-05-21 07:53 UTC, shpran commented on model/sharedStimulus/css/factory/CommandFactory.php
> +    public function makeLoadStylesheetCommandByRequest(ServerRequestInterface $request): LoadStylesheetResourceUri
This method creates a new instance of `LoadStylesheetCommand` and returns it.
We do not execute anything here.

2021-05-21 08:10 UTC, bartlomiejmarszal commented on model/sharedStimulus/css/GetStylesheetsCommand.php
> +class GetStylesheetsCommand implements ResourceUriInterface
There is no command here. This class allow to store uri. This name is confusing for me.

2021-05-21 08:10 UTC, bartlomiejmarszal commented on model/sharedStimulus/css/factory/CommandFactory.php
> +    public function makeGetStylesheetsCommandByRequest(ServerRequestInterface $request): GetStylesheetsResourceUri
When I read makeGetStylesheetsCommandByRequest I expect that you will make/generate some command with a help of request payload.

2021-05-21 08:15 UTC, bartlomiejmarszal requested changes
Because of class naming convection that you choose some of the method name doesn't take sense and are confusing.

2021-05-21 08:15 UTC, bartlomiejmarszal commented on model/sharedStimulus/css/factory/CommandFactory.php
> +        $this->validateParams($params, ['uri', 'stylesheetUri'],__METHOD__);
This ay throw an error and you. removed all throws tags Fromm annotations. Is that correct?

2021-05-21 08:15 UTC, bartlomiejmarszal commented on model/sharedStimulus/css/factory/CommandFactory.php
> +    public function makeLoadStylesheetCommandByRequest(ServerRequestInterface $request): LoadStylesheetCommand
You Making and loading?

2021-05-21 08:28 UTC, bartlomiejmarszal requested changes
Why did you removed all throws tags fro all methods?

2021-05-21 08:28 UTC, bartlomiejmarszal commented on controller/SharedStimulusStyling.php
> -    public function save(): void
Is this a braking change?

2021-05-21 08:28 UTC, bartlomiejmarszal commented on model/sharedStimulus/css/LoadStylesheetCommand.php
> +    public function getStylesheet(): string
This method is not included in interface. How do we manage to recognise when to use this and when dow we use correct inutrafec methods?

2021-05-21 08:28 UTC, bartlomiejmarszal commented on model/sharedStimulus/css/factory/CommandFactory.php
> -     * @throws MissingParameterException
This method still can throw MissingParameterException

2021-05-21 08:28 UTC, bartlomiejmarszal commented on model/sharedStimulus/css/service/StylesheetService.php
> +class StylesheetService extends ConfigurableCssService
```suggestion
class StylesheetLoaderService extends ConfigurableCssService
```

2021-05-21 10:47 UTC, pnal reviewed
Please put refactoring to a separate commits to split it from an actual solution implementation cause it's difficult to catch.
If it is final solution please add unit tests and document an API methods here:
https://github.com/oat-sa/extension-tao-mediamanager/blob/feature/aut-35/adding-rich-passages-styling/doc/taoMediaManagerApi.yml

2021-05-21 10:47 UTC, pnal commented on model/sharedStimulus/css/service/StylesheetService.php
> +    public function load(LoadStylesheetCommand $command): StreamInterface
We already have LoadService implemented for a custom stylesheets load which returns json with css classes
This method returns a file stream so let's rename it and split to separate eg. DownloadService

2021-05-21 10:47 UTC, pnal commented on model/sharedStimulus/css/service/StylesheetService.php
> +    public function getList(GetStylesheetsCommand $command): array
Let's try to avoid services with more then one public method.

2021-05-21 11:04 UTC, pnal requested changes

2021-05-21 11:04 UTC, pnal commented on model/sharedStimulus/css/service/ConfigurableCssService.php
> +abstract class ConfigurableCssService extends ConfigurableService
```suggestion
abstract class ConfigurableCssStorageService extends ConfigurableService
```
It may be smth like `Persistence` or `Data` cause it's responsibility is to keep data in FS/DB

2021-05-21 11:42 UTC, mike-ionut-mihai-sandu-tao commented on model/sharedStimulus/css/service/StylesheetService.php
> +    public function getList(GetStylesheetsCommand $command): array
i agree with the fact that we should keep solid as a base priciple but having only 1 public method is usually not possible or described in normal patterns

2021-05-24 13:35 UTC, pnal requested changes

2021-05-24 13:35 UTC, pnal commented on model/sharedStimulus/css/service/ListStylesheetsService.php
> +    public function getList(ListStylesheets $listStylesheetsRequest): array
```suggestion
    public function getList(ListStylesheets $listStylesheetsDTO): array
```

2021-05-24 13:35 UTC, pnal commented on model/sharedStimulus/css/service/ListStylesheetsService.php
> +        $path = $stylesheetRepository->getPath($listStylesheetsRequest->getUri());
```suggestion
        $path = $stylesheetRepository->getPath($listStylesheetsDTO->getUri());
```

2021-05-24 13:35 UTC, pnal commented on model/sharedStimulus/css/handler/SaveStylesheetClassesHandler.php
> +        if (!is_array($css)) {
Please move it to the validate method below

2021-05-24 13:35 UTC, pnal commented on model/sharedStimulus/css/service/LoadStylesheetClassesService.php
> +    public function load(LoadStylesheet $loadStylesheetRequest): array
```suggestion
    public function load(LoadStylesheet $loadStylesheetDTO): array
```

2021-05-24 13:35 UTC, pnal commented on model/sharedStimulus/css/service/LoadStylesheetClassesService.php
> +        $path = $stylesheetRepository->getPath($loadStylesheetRequest->getUri());
```suggestion
        $path = $stylesheetRepository->getPath($loadStylesheetDTO->getUri());
```

2021-05-24 13:35 UTC, pnal commented on model/sharedStimulus/css/service/LoadStylesheetClassesService.php
> +                $path . DIRECTORY_SEPARATOR . $loadStylesheetRequest->getStylesheetUri()
```suggestion
                $path . DIRECTORY_SEPARATOR . $loadStylesheetDTO->getStylesheetUri()
```

2021-05-24 13:35 UTC, pnal commented on model/sharedStimulus/css/service/LoadStylesheetClassesService.php
> +                    $loadStylesheetRequest->getUri(),
```suggestion
                    $loadStylesheetDTO->getUri(),
```

2021-05-24 13:35 UTC, pnal commented on model/sharedStimulus/css/service/LoadStylesheetClassesService.php
> +                    $loadStylesheetRequest->getStylesheetUri()
```suggestion
                    $loadStylesheetDTO->getStylesheetUri()
```

2021-05-24 13:35 UTC, pnal commented on model/sharedStimulus/css/service/SaveStylesheetClassesService.php
> +    public function save(SaveStylesheetClasses $saveStylesheetClassesRequest): void
```suggestion
    public function save(SaveStylesheetClasses $saveStylesheetClassesDTO): void
```

2021-05-24 13:35 UTC, pnal commented on model/sharedStimulus/css/service/SaveStylesheetClassesService.php
> +        $path = $this->getStylesheetRepository()->getPath($saveStylesheetClassesRequest->getUri());
```suggestion
        $path = $this->getStylesheetRepository()->getPath($saveStylesheetClassesDTO->getUri());
```

2021-05-24 13:35 UTC, pnal commented on model/sharedStimulus/css/service/SaveStylesheetClassesService.php
> +        $cssClassesArray = $saveStylesheetClassesRequest->getCssClassesArray();
```suggestion
        $cssClassesArray = $saveStylesheetClassesDTO->getCssClassesArray();
```

2021-05-24 13:35 UTC, pnal commented on model/sharedStimulus/css/service/SaveStylesheetClassesService.php
> +            $this->removeStoredStylesheet($path . DIRECTORY_SEPARATOR . $saveStylesheetClassesRequest->getStylesheetUri());
Same as above

2021-05-24 13:35 UTC, pnal commented on model/validation/RequestValidator.php
> +    public static function validateRequiredParameters(array $params, array $requiredParams): void
phpDoc exceptions

2021-05-24 14:17 UTC, pnal approved these changes
LGTM

- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2021-05-24 14:29 UTC, AntonNeviarouski commented
QA verified on http://test-shpran.playground.kitchen.it.taocloud.org:41481/

2021-05-24 14:31 UTC, merged