Feature/AUT-36/Import & export items with rich passages
oat-sa/extension-tao-mediamanager pull request #276
Opened 2021-05-31 01:48 UTC by shpran

2021-05-31 07:26 UTC, mike-ionut-mihai-sandu-tao commented on model/SharedStimulusPackageImporter.php
> +    public function getSharedStimulusStylesheets(string $extractPath): array
are you sure we change the visibility ?

2021-05-31 07:30 UTC, mike-ionut-mihai-sandu-tao commented on model/MediaSource.php
> +    public function addSharedStimulus(string $source, string $parent, string $absolutePath): array
can we add tests ?

2021-05-31 07:30 UTC, mike-ionut-mihai-sandu-tao commented on model/MediaSource.php
> +        if (!file_exists($source)) {
can we or should we use the fly-system abstraction for this just not to couple this to the local folder system?

2021-05-31 07:30 UTC, mike-ionut-mihai-sandu-tao commented on model/MediaSource.php
> +            throw new tao_models_classes_FileNotFoundException($source);
maybe let's import and use a alias

2021-05-31 07:30 UTC, mike-ionut-mihai-sandu-tao commented on model/MediaSource.php
> +        $sharedStimulusPackageImporter->setServiceLocator($this->getServiceLocator());
maybe let's extract this ?

2021-05-31 07:30 UTC, mike-ionut-mihai-sandu-tao commented on model/export/service/SharedStimulusCSSExporter.php
> +    public function getResourceLink(core_kernel_classes_Resource $resource)
return hint if possible

2021-05-31 07:30 UTC, mike-ionut-mihai-sandu-tao commented on model/export/service/SharedStimulusCSSExporter.php
> +    public function getResourceLink(core_kernel_classes_Resource $resource)
also a alias would be nice

2021-05-31 07:40 UTC, bartlomiejmarszal commented on model/MediaSource.php
> +            throw new tao_models_classes_FileNotFoundException($source);
I'm not encouraging anybody to do so. I prefer to know exact class that is throwed here instead of searching this in import block.

2021-05-31 08:54 UTC, bartlomiejmarszal requested changes
I have few comment. To be continued.

2021-05-31 08:54 UTC, bartlomiejmarszal commented on model/MediaSource.php
> +        $sharedStimulusPackageImporter->setServiceLocator($this->getServiceLocator());
I don't like how we are using this importer. Are you sure there is no service locator that use this importer as engine?

2021-05-31 08:54 UTC, bartlomiejmarszal commented on model/ZipExporter.php
> -                    $this->getSharedStimulusCSSExporter()->pack($fileResource, $link, $zip);
Why did you removed this param?

2021-05-31 08:54 UTC, bartlomiejmarszal commented on model/export/service/SharedStimulusCSSExporter.php
> +    public function pack(
You removed parameter from public method that may have dependencies you are not aware of. This is braking change in my opinion

2021-05-31 16:15 UTC, pnal reviewed
Added a few comments

2021-05-31 16:15 UTC, pnal commented on model/export/service/SharedStimulusCSSExporter.php
> +    public function pack(
Added my doubts about it here: https://github.com/oat-sa/extension-tao-itemqti/pull/1754#discussion_r642579540

2021-05-31 16:15 UTC, pnal commented on model/export/service/SharedStimulusCSSExporter.php
> +    public function getResourceLink(core_kernel_classes_Resource $resource)
I don't think we really need get a resource link in this class and even more make this method public.

2021-06-02 10:05 UTC, bartlomiejmarszal commented on model/export/service/SharedStimulusCSSExporter.php
> +use oat\taoMediaManager\model\MediaService;
We are introducing dependency to MediaManager extension here

2021-06-07 18:55 UTC, closed without merging