[E2E testing] Be able to perform various actions on classes
oat-sa/extension-tao-mediamanager pull request #297
Opened 2021-07-23 11:00 UTC by habemuscode

**Ticket**

https://oat-sa.atlassian.net/browse/ADF-555

2021-07-28 10:04 UTC, clagosarias approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [ ]  New code is not subject to concurrency issues (if applicable)
- [ ]  The feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request's target is not master
- [x]  Pull request title and description are meaningful
- [x]  Commits are following conventional commits
- [x]  Kitchen links are not exposed in the description

2021-07-28 13:50 UTC, bziondik requested changes
Add removing  of class `Test E2E class Moved`, can be in hook `after`
Also in my case test fails because of timeout and I see 3 class, should be removed
![image](https://user-images.githubusercontent.com/25976342/127333801-53866453-794a-43f7-ba33-e212d7afa451.png)

2021-08-10 06:09 UTC, 404passionFruit approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] The feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request's target is not `master`
- [x] Pull request title and description are meaningful
- [x] Commits are following conventional commits
- [x] Kitchen links are not exposed in the description

2021-08-12 13:31 UTC, 404passionFruit approved these changes

2021-08-12 14:14 UTC, merged