feat: atomic roles for asset management
oat-sa/extension-tao-mediamanager pull request #298
Opened 2021-07-23 12:34 UTC by chinnu-focaloid

Relates to : https://oat-sa.atlassian.net/browse/ADF-208
Atomic roles list:
- Asset class navigator
- Asset viewer
- Asset exporter
- Asset previewer
- Asset properties editor
- Asset content creator

2021-07-26 05:40 UTC, gabrielfs7 commented on composer.json
> +				"oat\\taoMediaManager\\model\\": "model/classes/"
Why was it necessary? We were able to load the classes before.

2021-07-26 05:44 UTC, gabrielfs7 commented on controller/MediaManager.php
> +        }
Please, lets avoid else/if, cause it increases the code complexity and can always be replaced by early return in proper method.

https://williamdurand.fr/2013/06/03/object-calisthenics/#2-dont-use-the-else-keyword

2021-07-26 05:46 UTC, gabrielfs7 commented on migrations/Version202107161250081888_taoMediaManager.php
> +final class Version202107161250081888_taoMediaManager extends AbstractMigration
Remove always, please. It is not necessary.

```suggestion
final class Version202107161250081888_taoMediaManager extends AbstractMigration
```

2021-07-26 05:47 UTC, gabrielfs7 commented on model/editInstanceForm.php
> +        return empty($this->options[self::IS_REPLACE_ASSET_DISABLED] ?? false);
Why we are not considering `self::IS_DISABLED` anymore? Also, imagine that even if `replacement` is not allowed, the four could be enabled, no?

2021-07-26 05:49 UTC, gabrielfs7 commented on model/ontology/taomedia.rdf
> +  <rdf:Description rdf:about="http://www.tao.lu/Ontologies/TAOMedia.rdf#AssetRole">
isn't `AssetRole` too generic? It is like create a role called `ItemRole`. It does not meany anything and means everything at the same time. Can we find a better name?

2021-07-26 05:51 UTC, gabrielfs7 commented on views/templates/form.tpl
> +    <?php endif; ?>
We can simplify and avoid repeat the code:

```suggestion
    <div class="data-container-wrapper flex-container-remaining" style="display:<?php echo has_data('isPreviewEnabled') ? 'block' : 'none'; ?>">
```

2021-07-26 05:51 UTC, gabrielfs7 requested changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2021-07-26 06:12 UTC, boajer commented on migrations/Version202107161250081888_taoMediaManager.php
> +
```suggestion

```

2021-07-26 06:49 UTC, chinnu-focaloid commented on model/ontology/taomedia.rdf
> +  <rdf:Description rdf:about="http://www.tao.lu/Ontologies/TAOMedia.rdf#AssetRole">
Can rename it as AssetManagementRole or ManageAssetRole? What do you think?

2021-07-26 06:57 UTC, chinnu-focaloid commented on model/editInstanceForm.php
> +        return empty($this->options[self::IS_REPLACE_ASSET_DISABLED] ?? false);
We are considering both. IS_DISABLED is used in general like for disable Save button.
IS_REPLACE_ASSET_DISABLED is used only for checking 'Replace asset button.'
Here , the isEnabled() function is called only from getReplaceAssetButtonTemplate() to check replace button is enabled or not.

2021-07-26 07:02 UTC, gabrielfs7 commented on model/ontology/taomedia.rdf
> +  <rdf:Description rdf:about="http://www.tao.lu/Ontologies/TAOMedia.rdf#AssetRole">
To follow the approach we have for Items, I would call it `AssetsManager`, wdyt?

2021-07-26 07:05 UTC, chinnu-focaloid commented on model/ontology/taomedia.rdf
> +  <rdf:Description rdf:about="http://www.tao.lu/Ontologies/TAOMedia.rdf#AssetRole">
Definitely. I will rename is as `AssetsManager`

2021-07-26 07:05 UTC, gabrielfs7 commented on model/editInstanceForm.php
> +        return empty($this->options[self::IS_REPLACE_ASSET_DISABLED] ?? false);
Do not you think this is a bit confuse? Should not we have a method `isReplaceEnabled` instead and keep the isEnabled as before? Cause we have many other actions in the form, like changing label, language and alternative text.

2021-07-26 07:09 UTC, chinnu-focaloid commented on model/editInstanceForm.php
> +        return empty($this->options[self::IS_REPLACE_ASSET_DISABLED] ?? false);
Sure. I will add a new method and keep it as before.

2021-07-26 10:03 UTC, chinnu-focaloid commented on composer.json
> +				"oat\\taoMediaManager\\model\\": "model/classes/"
Done

2021-07-26 10:03 UTC, chinnu-focaloid commented on controller/MediaManager.php
> +        }
Done

2021-07-26 10:03 UTC, chinnu-focaloid commented on migrations/Version202107161250081888_taoMediaManager.php
> +final class Version202107161250081888_taoMediaManager extends AbstractMigration
Done

2021-07-26 10:03 UTC, chinnu-focaloid commented on model/editInstanceForm.php
> +        return empty($this->options[self::IS_REPLACE_ASSET_DISABLED] ?? false);
Done

2021-07-26 10:04 UTC, chinnu-focaloid commented on model/ontology/taomedia.rdf
> +  <rdf:Description rdf:about="http://www.tao.lu/Ontologies/TAOMedia.rdf#AssetRole">
Done

2021-07-26 10:04 UTC, chinnu-focaloid commented on views/templates/form.tpl
> +    <?php endif; ?>
Done

2021-07-26 10:04 UTC, chinnu-focaloid commented on migrations/Version202107161250081888_taoMediaManager.php
> +
Done

2021-07-26 12:22 UTC, gabrielfs7 commented on model/ontology/taomedia.rdf
> +  <rdf:Description rdf:about="http://www.tao.lu/Ontologies/TAOMedia.rdf#AssetsManager">
Lets rename back to `AssetRole`, cause I though this was a role, but it is actually a class :)

2021-07-28 07:49 UTC, shpran commented on migrations/Version202107161250081888_taoMediaManager.php
> +                    TaoAssetRoles::ASSET_CONTENT_CREATOR => ActionAccessControl::READ,
If I'm not mistaken, `ASSET_VIEWER` and `ASSET_PROPERTIES_EDITOR` will be enough.
Because `ASSET_PREVIEWER` and `ASSET_CONTENT_CREATOR` includes `ASSET_VIEWER` role.
Can you check this, please?

```suggestion
                    TaoAssetRoles::ASSET_VIEWER => ActionAccessControl::READ,
                    TaoAssetRoles::ASSET_PROPERTIES_EDITOR => ActionAccessControl::WRITE,
```

2021-07-28 07:49 UTC, shpran commented on manifest.php
> +            TaoAssetRoles::ITEM_AUTHOR,
We have this role declared in `extension-tao-item`: https://github.com/oat-sa/extension-tao-item/blob/develop/models/classes/user/TaoItemsRoles.php#L27

As I see, `extension-tao-mediamanager` require `extension-tao-item` in composer.json, so maybe we can use this constant instead of creating a new one?
Wdyt? @chinnu-focaloid @gabrielfs7

2021-07-28 07:49 UTC, shpran commented on model/editInstanceForm.php
> +        return empty($this->options['is_replace_asset_disabled'] ?? false);
Can we use a constant instead of `is_replace_asset_disabled` string?

2021-07-28 07:52 UTC, gabrielfs7 commented on migrations/Version202107161250081888_taoMediaManager.php
> +                    TaoAssetRoles::ASSET_CONTENT_CREATOR => ActionAccessControl::READ,
Unfortunately they do not extend ASSET_VIEWER @shpran :/

https://oat-sa.atlassian.net/browse/ADF-208

2021-07-28 07:53 UTC, gabrielfs7 commented on manifest.php
> +            TaoAssetRoles::ITEM_AUTHOR,
Yes, we should not create it here for sure

2021-07-28 07:59 UTC, shpran commented on migrations/Version202107161250081888_taoMediaManager.php
> +                    TaoAssetRoles::ASSET_CONTENT_CREATOR => ActionAccessControl::READ,
@gabrielfs7 

| # | Role | Includes |
| -- | -- | -- |
| `AR1` | Asset viewer | ACR1 |
| AR3 | Asset previewer | AR1 |
| AR4 | Asset properties editor | `AR1` |
| AR7 | Asset content creator | `AR1` |

2021-07-28 08:16 UTC, gabrielfs7 commented on migrations/Version202107161250081888_taoMediaManager.php
> +                    TaoAssetRoles::ASSET_CONTENT_CREATOR => ActionAccessControl::READ,
Yes, you are completely right. I was blind, but now I see :)

2021-07-28 08:44 UTC, shpran commented on migrations/Version202107161250081888_taoMediaManager.php
> +                ['ext' => 'taoMediaManager', 'mod' => 'MediaManager', 'act' => 'editInstance'],
I'm not sure, but maybe we don't need this asset rule, because ASSET_VIEWER already has it.
Can you please check this?

2021-07-28 08:44 UTC, shpran commented on migrations/Version202107161250081888_taoMediaManager.php
> +                ['ext' => 'taoMediaManager', 'mod' => 'MediaManager', 'act' => 'editInstance'],
Same: https://github.com/oat-sa/extension-tao-mediamanager/pull/298/files#r678100578

2021-07-28 12:19 UTC, gabrielfs7 commented on model/ontology/taomedia.rdf
> +
```suggestion
 ```

2021-07-28 12:23 UTC, gabrielfs7 commented on model/classes/user/TaoAssetRoles.php
> +    public const ITEM_AUTHOR = 'http://www.tao.lu/Ontologies/TAOItem.rdf#ItemAuthor';
We should use role from taoItems

2021-07-28 23:22 UTC, chinnu-focaloid commented on manifest.php
> +            TaoAssetRoles::ITEM_AUTHOR,
Done

2021-07-28 23:26 UTC, chinnu-focaloid commented on model/ontology/taomedia.rdf
> +
Done

2021-07-28 23:26 UTC, chinnu-focaloid commented on model/classes/user/TaoAssetRoles.php
> +    public const ITEM_AUTHOR = 'http://www.tao.lu/Ontologies/TAOItem.rdf#ItemAuthor';
Done

2021-07-28 23:37 UTC, chinnu-focaloid commented on migrations/Version202107161250081888_taoMediaManager.php
> +                ['ext' => 'taoMediaManager', 'mod' => 'MediaManager', 'act' => 'editInstance'],
Yes. We can. Removed.

2021-07-28 23:41 UTC, chinnu-focaloid commented on migrations/Version202107161250081888_taoMediaManager.php
> +                ['ext' => 'taoMediaManager', 'mod' => 'MediaManager', 'act' => 'editInstance'],
Done

2021-07-28 23:48 UTC, chinnu-focaloid commented on model/editInstanceForm.php
> +        return empty($this->options['is_replace_asset_disabled'] ?? false);
Done

2021-07-28 23:49 UTC, chinnu-focaloid commented on migrations/Version202107161250081888_taoMediaManager.php
> +                    TaoAssetRoles::ASSET_CONTENT_CREATOR => ActionAccessControl::READ,
Done

2021-07-29 09:11 UTC, gabrielfs7 commented on model/mapper/MediaSourcePermissionsMapper.php
> +                \taoItems_actions_ItemContent::class,
FQN

2021-07-29 09:11 UTC, gabrielfs7 commented on model/mapper/MediaSourcePermissionsMapper.php
> +                'files'
FQN

2021-07-29 12:38 UTC, gabrielfs7 approved these changes
LGTM

2021-07-29 12:39 UTC, gabrielfs7 commented
@chinnu-focaloid , please do not forget to add proper dependency on `composer.json`

2021-07-29 12:40 UTC, gabrielfs7 commented on model/mapper/MediaSourcePermissionsMapper.php
> +class MediaSourcePermissionsMapper extends MediaBrowserPermissionsMapper
tests?

2021-07-29 13:00 UTC, shpran approved these changes
Do not forget to update `composer.json` with new versions before merging.

- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2021-07-29 13:02 UTC, shpran commented on model/mapper/MediaSourcePermissionsMapper.php
> +class MediaSourcePermissionsMapper extends MediaBrowserPermissionsMapper
As this was done only to test Authoring and we need to change this to split `add` and `delete` - maybe we can add tests during [this task](https://oat-sa.atlassian.net/browse/ADF-573)?

2021-07-29 14:00 UTC, gabrielfs7 commented on model/mapper/MediaSourcePermissionsMapper.php
> +class MediaSourcePermissionsMapper extends MediaBrowserPermissionsMapper
ok :)

2021-07-30 06:33 UTC, AntonNeviarouski commented
QA verified on http://test-chinnufrancis.playground.kitchen.it.taocloud.org:48831/tao/Main/login

2021-07-30 08:55 UTC, AntonNeviarouski commented
QA re-verified on http://test-chinnufrancis.playground.kitchen.it.taocloud.org:48831/tao/Main/login

2021-07-30 10:12 UTC, merged