Fix/ADF-627/Reconfigure Asset Content Creator role permissions
oat-sa/extension-tao-mediamanager pull request #312
Opened 2021-08-27 15:36 UTC by shpran

**Relates to:** _[ADF-627](https://oat-sa.atlassian.net/browse/ADF-627)_

---

**Changes:**
* `files`, `upload` and `delete` permissions revoked;
* `viewAsset` permission added;
* Check for `viewAsset` read access during permissions mapper.

---

**Companion PRs:**
* https://github.com/oat-sa/extension-tao-item/pull/512
* https://github.com/oat-sa/tao-core/pull/3085

2021-08-31 10:49 UTC, AntonNeviarouski commented
QA verified on http://test-shpran.playground.kitchen.it.taocloud.org:41481/

2021-09-01 00:42 UTC, chinnu-focaloid approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [X] New code is respecting code style rules
- [X] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [X] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2021-09-01 08:55 UTC, gabrielfs7 commented on model/classes/user/TaoAssetRoles.php
> + * @deprecated Use \oat\taoMediaManager\model\user\TaoAssetRoles
Why we have 2 interfaces? I saw that the `oat\taoMediaManager\model\user\TaoAssetRoles` was create recently and is basically duplicating all the constants we had? What is the reason for it?

2021-09-01 09:36 UTC, gabrielfs7 commented on model/classes/user/TaoAssetRoles.php
>  interface TaoAssetRoles
Please, do not duplicated the constants. Instead extend the proper interface:

```suggestion
interface TaoAssetRoles extends \oat\taoMediaManager\model\user\TaoAssetRoles
```

And then remove the constants

2021-09-01 09:47 UTC, gabrielfs7 approved these changes

2021-09-01 09:48 UTC, gabrielfs7 requested changes
Fix broken tests, please :)

2021-09-01 11:18 UTC, gabrielfs7 commented on test/unit/model/mapper/MediaSourcePermissionsMapperTest.php
> +                'permissions' => [],
The test does not make sense anymore based on the title `testMapWithOnlyReadAndWritePermissions`.

2021-09-01 13:48 UTC, gabrielfs7 approved these changes

2021-09-02 09:26 UTC, merged