Feature/aut 1195/e2e add asset passage to interaction
oat-sa/extension-tao-mediamanager pull request #359
Opened 2021-11-26 16:37 UTC by Silvia-loza

**End to end testing.**
Related to: https://oat-sa.atlassian.net/browse/AUT-1195
Depends on :

**Description of changes:**
Creation of E2E tests for: Creating and importing passages/asset and adding to prompt and choice of interaction
**How to run locally:**
Checkout to branch  `feature/AUT-1195/e2e-add-asset-passage-to-interaction`
in extensions:

- https://github.com/oat-sa/tao-core
- https://github.com/oat-sa/extension-tao-itemqti
- https://github.com/oat-sa/extension-tao-mediamanager

**run tests from tao core extn:**
npm run[ cy:open](url) - to run in browser
or npm run` cy:run` - for headless execution
File to test: `add-asset-passage-to-interaction.spec.js`
All tests should pass:
![image](https://user-images.githubusercontent.com/60346520/143610096-73afab82-8e72-4970-9589-e21cb06c807b.png)

2021-12-01 12:52 UTC, adriloma approved these changes
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following conventional commits
- [x] Commits messages are meaningful
- [x] Commits are atomic

2021-12-02 07:58 UTC, bziondik requested changes

2021-12-02 07:58 UTC, bziondik commented on views/cypress/tests/add-asset-passage-to-interaction.spec.js
> +             cy.get(`${selectors.manageAssets}`).click();
Next test failed because of this line. UI doesn't know that save was successful, first check that Save button is enabled
![image](https://user-images.githubusercontent.com/25976342/144379748-9da05f90-4bb4-4759-be53-a33484dd11b6.png)
![image](https://user-images.githubusercontent.com/25976342/144379821-38dde031-e698-48bb-a745-22404ebfea31.png)

2021-12-02 07:58 UTC, bziondik commented on views/cypress/tests/add-asset-passage-to-interaction.spec.js
> +            const isCreatedAsset = true;
This test fails for me sometimes
![image](https://user-images.githubusercontent.com/25976342/144380126-dff0e2cf-4177-47ce-9215-bf60539f99ec.png)

2021-12-02 07:58 UTC, bziondik commented on views/cypress/tests/add-asset-passage-to-interaction.spec.js
> +        it('can add imported asset to the prompt ', function () {
This test fails for me sometimes
![image](https://user-images.githubusercontent.com/25976342/144380228-e722b967-c2b9-4cf6-b2fa-61e4874b629c.png)

2021-12-03 12:34 UTC, bziondik approved these changes
- [x]  New code is covered by tests (if applicable)
- [x]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful
![image](https://user-images.githubusercontent.com/25976342/144603301-79887812-72b3-48b1-a5ba-02700832a219.png)

2021-12-03 16:14 UTC, merged