fix: hotfix - AUT-1620 added script migrating old passages to store i…
oat-sa/extension-tao-mediamanager pull request #366
Opened 2021-12-17 14:31 UTC by pnal

…n subdirectory

2021-12-17 14:51 UTC, andreluizmachado requested changes

2021-12-17 14:51 UTC, andreluizmachado commented on scripts/ReplaceSharedStimulusMedia.php
> +        $dryRun = isset($params[0]) && strpos($params[0], 'dryRun') !== false;
Why are you using strpos? why do not we compare the entire string?

2021-12-17 14:51 UTC, andreluizmachado commented on scripts/ReplaceSharedStimulusMedia.php
> +class ReplaceSharedStimulusMedia extends ConfigurableService implements Action
can we add automated tests for this class?

2021-12-17 14:51 UTC, andreluizmachado commented on scripts/ReplaceSharedStimulusMedia.php
> +<?php
shouldn't we create a migration for this script?

2021-12-20 11:56 UTC, andreluizmachado commented on scripts/ReplaceSharedStimulusMedia.php
> +<?php
please check: https://oat-sa.atlassian.net/browse/AUT-1620?focusedCommentId=165847

2021-12-20 11:56 UTC, andreluizmachado commented on scripts/ReplaceSharedStimulusMedia.php
> +<?php
please check: https://oat-sa.atlassian.net/browse/AUT-1620?focusedCommentId=165847

2021-12-20 11:57 UTC, andreluizmachado commented on scripts/ReplaceSharedStimulusMedia.php
> +class ReplaceSharedStimulusMedia extends ConfigurableService implements Action
Please check: https://oat-sa.atlassian.net/browse/AUT-1620?focusedCommentId=165847

2021-12-20 11:57 UTC, andreluizmachado commented on scripts/ReplaceSharedStimulusMedia.php
> +        $dryRun = isset($params[0]) && strpos($params[0], 'dryRun') !== false;
Please check: https://oat-sa.atlassian.net/browse/AUT-1620?focusedCommentId=165847

2021-12-20 11:58 UTC, andreluizmachado approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2021-12-20 14:39 UTC, bziondik approved these changes
LGTM

2021-12-20 14:41 UTC, merged