refactor: moved passage asset encoding out of SharedStimulusPackageIm…
oat-sa/extension-tao-mediamanager pull request #391
Opened 2022-04-06 08:35 UTC by pnal

…porter as a service

2022-04-07 11:35 UTC, bartlomiejmarszal requested changes
in `model/SharedStimulusPackageImporter.php` please update licence copyright dates

Please provide test for `model/sharedStimulus/encoder/SharedStimulusMediaEncoder.php`.
This class should also be following DI.

2022-04-07 11:35 UTC, bartlomiejmarszal commented on model/sharedStimulus/encoder/SharedStimulusMediaEncoder.php
> +    }
```suggestion
protected function secureEncode(string $basedir, string $source): string
    {
        $components = parse_url($source);

        if (!isset($components['scheme'])) {
            $this->validateSourceSecurity($basedir, $source);
                    return 'data:' . tao_helpers_File::getMimeType($basedir . $source) . ';'
                        . 'base64,' . base64_encode(file_get_contents($basedir . $source));
        }

        return $source;
    }
    
    private function validateSourceSecurity(string $basedir, string $source): void
    {
        if (!tao_helpers_File::securityCheck($source, false)) {
            throw new tao_models_classes_FileNotFoundException($source);
        }

        if (file_exists($basedir . $source)) {
            throw new common_exception_Error('Invalid source path "' . $source . '"');
        }
    }
```

2022-04-07 11:35 UTC, bartlomiejmarszal commented on scripts/install/RegisterSharedStimulusMediaEncoder.php
> +        $serviceManager->register(SharedStimulusMediaEncoderInterface::SERVICE_ID, $SharedStimulusMediaEncoder);
```suggestion
        $this->getServiceManager()->register(SharedStimulusMediaEncoderInterface::SERVICE_ID, $SharedStimulusMediaEncoder);
```

2022-04-07 14:01 UTC, pnal commented on model/sharedStimulus/encoder/SharedStimulusMediaEncoder.php
> +class SharedStimulusMediaEncoder extends ConfigurableService implements SharedStimulusMediaEncoderInterface
Because I need to replace implementation of this services by other extension

2022-04-08 07:05 UTC, bartlomiejmarszal commented on model/sharedStimulus/encoder/SharedStimulusMediaEncoder.php
> +class SharedStimulusMediaEncoder extends ConfigurableService implements SharedStimulusMediaEncoderInterface
And why you are not using DI?

2022-04-08 13:05 UTC, bartlomiejmarszal approved these changes

2022-04-08 14:12 UTC, merged