feat: copy source from taoQtiItem
oat-sa/extension-tao-mediamanager pull request #403
Opened 2022-05-30 14:53 UTC by bziondik

Depends on: 

- [ ] https://github.com/oat-sa/extension-tao-itemqti/pull/2138

2022-06-01 16:37 UTC, marpesia requested changes
The FE works great.

I've checked locally, and I found some issues:
- Add some text paragraphs
- Add an Image at the end of a paragraph line
- Uncheck the Responsive mode of Img
The Height is NaN, but it is working. If I change the Width, it changes the Hight.
I've checked if the Img is added out of the paragraph zone and it doesn't happen. If I first add the Image at the end, and later a second in the paragraphs, it doesn't happen too.
![image](https://user-images.githubusercontent.com/11692751/171452259-f8f9b1f0-0f1f-400e-b104-cae3ec9fe9bc.png)

I can't save the Asset if it contains an Img, I don't know if I missed something on the installation.
![image](https://user-images.githubusercontent.com/11692751/171453170-8efb582f-a82a-480f-8f50-280797f38f68.png)

In Kitchen, on adding an Image. Can you see the same?
![image](https://user-images.githubusercontent.com/11692751/171560314-a6067ea4-ba2d-4681-a9f1-165c3dfb8bb1.png)

2022-06-01 16:37 UTC, marpesia commented on views/js/qtiCreator/widgets/static/figure/states/states.js
> +    'taoMediaManager/qtiCreator/widgets/static/figure/states/Active'
Does the file on `taoQtiItem/views/js/qtiCreator/widgets/static/figure/states/Active.js` the same as on `'taoMediaManager/qtiCreator/widgets/static/figure/states/Active'` ?

2022-06-02 05:37 UTC, marpesia commented on views/js/qtiCreator/widgets/static/figure/states/states.js
> +    'taoMediaManager/qtiCreator/widgets/static/figure/states/Active'
Update: I can't see the NaN issue on Items on Kitchen, but I see it on Items on Local. So maybe there is something wrong with my local with that.

2022-06-02 07:49 UTC, marpesia commented on views/js/qtiCreator/widgets/static/figure/states/states.js
> +    'taoMediaManager/qtiCreator/widgets/static/figure/states/Active'
Update, adding this extension I can reproduce local and kitchen the same issue on Items and Assets.
It is the 1st time you unchecked the 'Responsive mode', the functionality is there, it is just the 1st time, and there is no correct value for that field.
![image](https://user-images.githubusercontent.com/11692751/171580902-0dfb5836-d49f-4737-a71d-627f33873daf.png)

2022-06-02 14:34 UTC, Silvia-loza commented
Code looks good and most things work as expected in local , however found this edge case in passage. :arrow_down: :arrow_down: 
![image](https://user-images.githubusercontent.com/60346520/171653585-0b098e07-c8c3-43d8-88e5-564dd7261a2e.png)

2022-06-08 13:21 UTC, marpesia approved these changes
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [ ] Pull request's target is not `master`
- [ ] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Commits messages are meaningful
- [ ] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2022-06-08 15:38 UTC, Silvia-loza approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [X] New code is respecting code style rules
- [X] New code is respecting best practices
- [X]  Pull request's target is not` master`
- [X] New code is not subject to concurrency issues (if applicable)
- [X] Feature is working correctly on my local machine (if applicable)
- [X] Acceptance criteria are respected
- [X] Pull request title and description are meaningful

2022-06-13 08:50 UTC, merged