Feat/aut 76/stylesheet manager for passages
oat-sa/extension-tao-mediamanager pull request #404
Opened 2022-06-01 08:22 UTC by marpesia

Related [AUT-76](https://oat-sa.atlassian.net/browse/AUT-76)

2022-06-27 06:29 UTC, bziondik commented on views/js/qtiCreator/sharedStimulusCreator.js
> +                                sharedStimulusCreator.hashClass = styleEditor.getMainClass();
maybe use `sharedStimulusCreator.mainClass`?

2022-06-27 06:29 UTC, bziondik commented on views/js/previewer/component/qtiSharedStimulusItem.js
> +                                assetClassName = styleEditor.generateMainClass();
Could be the case that passage don't have hasClass/mainClass but has uploaded stylesheets?

2022-06-27 06:29 UTC, bziondik commented on views/js/qtiCreator/component/tpl/sharedStimulusAuthoring.tpl
> +                                        <span id="item-editor-font-size-changer" data-target="body div.qti-item .mainClass .custom-text-box.hashClass > *">
Please check `sup`, `sub` elements. I remember was some issue with font-size and `*` selector

2022-06-27 06:29 UTC, bziondik commented on views/js/qtiCreator/sharedStimulusCreator.js
> +                                    $('link[data-serial*="creator"').each((i, style) => {
The same block of code was in `views/js/previewer/component/qtiSharedStimulusItem.js`
Can you move it to separate file?

2022-06-27 06:29 UTC, bziondik commented on views/js/richPassage/helpers.js
> +                                }, 1000);
could be less? like 100?

2022-06-27 06:43 UTC, bziondik requested changes
Check Unit tests
<img width="824" alt="image" src="https://user-images.githubusercontent.com/25976342/175875976-a333b5fb-7b7d-442c-b971-8abcd368e043.png">

2022-06-27 10:26 UTC, marpesia commented on views/js/richPassage/helpers.js
> +                                }, 1000);
I've reduced as much as possible, but I must wait until the CSS is loaded.

2022-08-09 11:25 UTC, bziondik approved these changes
- [x]  New code is covered by tests (if applicable)
- [x]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful
<img width="770" alt="image" src="https://user-images.githubusercontent.com/25976342/183636025-74e905ca-72b0-44c2-af2f-3c023be64efb.png">

Small improvements in comment

2022-08-09 11:25 UTC, bziondik commented on views/js/qtiCreator/helper/formatStyles.js
> +            const stylesheetUrl = linkTag.href.split('&stylesheet=');
Maybe better to use this?
const urlParams = new URLSearchParams(stylesheetUrl);
const page_type = urlParams.get('stylesheet')

2022-08-09 11:25 UTC, bziondik commented on views/js/richPassage/xincludeRendererAddStyles.js
>                              'data-serial': passageUri
```suggestion
                            'data-serial': serial
```

instead of `styleElem[0].dataset['serial'] = serial;`

2022-08-10 07:45 UTC, marpesia commented on views/js/qtiCreator/helper/formatStyles.js
> +            const stylesheetUrl = linkTag.href.split('&stylesheet=');
The problem is that I need the Asset identifier number that is on the `href` but it has no specific param. It is just before the stylesheet. 
![image](https://user-images.githubusercontent.com/11692751/183843921-3def0875-392a-4061-ab22-e34e548974a9.png)

2022-08-10 07:55 UTC, marpesia commented on views/js/richPassage/xincludeRendererAddStyles.js
>                              'data-serial': passageUri
This function is called by the Item Authoring and the Passage Preview on the Shared Stimulus Resource Manager modal on the Item Authoring.
It hasn't got the same scope. If you see, I've done a condition on line 48, and I only need to set the serial and call the `onload` function when the Item authoring calls it. The Resource Manager has an iframe that contains the CSS files, so there is no need to call extra formating functions. And in this case, the serial value is empty.

2022-08-10 08:53 UTC, bziondik commented on views/js/qtiCreator/helper/formatStyles.js
> +            const stylesheetUrl = linkTag.href.split('&stylesheet=');
Asset identifier number is sub-sting of uri param, you need to decode it

2022-08-10 10:36 UTC, marpesia commented on views/js/qtiCreator/helper/formatStyles.js
> +            const stylesheetUrl = linkTag.href.split('&stylesheet=');
The problem is that baseURI is not the same on Previews for example, but href doesn't change
![image](https://user-images.githubusercontent.com/11692751/183881238-c6cc69a9-b2df-4e4d-b1bd-a56e38ab8135.png)

2022-08-12 13:57 UTC, meefox approved these changes
Front end part
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [ ] Pull request's target is not `master`
- [ ] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Commits messages are meaningful
- [ ] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2022-08-17 11:01 UTC, merged