fix: remove * from data-target so styles don't get to children elements
oat-sa/extension-tao-mediamanager pull request #424
Opened 2022-09-26 14:44 UTC by Silvia-loza

**RELATED TO:**
AUT: 2639 [https://oat-sa.atlassian.net/browse/AUT-2639](url)
AUT-2653 [https://oat-sa.atlassian.net/browse/AUT-2653](url)
AUT-2654 [https://oat-sa.atlassian.net/browse/AUT-2654](url)

**STEPS TO TEST:**
1. Create  Passage add texto and an image
2. change the background color, or any other colors in color picker
3. Click on image

**CURRENT RESULT:**
- Background color doesn't apply to all background but seems broken

- When image active, bin button inherits styles: background color and padding, resutling on a bigger size.

**EXPECTED RESULT:**
- Background color is uniform and affect all text  background.

- When focusing on image, bin icon stays standard color and size
![image](https://user-images.githubusercontent.com/60346520/192306079-1b9aea9f-101a-42a8-8a85-d7e15ba48d8f.png)

2022-09-26 14:50 UTC, marpesia requested changes
Please check this

2022-09-26 14:50 UTC, marpesia commented on views/js/qtiCreator/component/tpl/sharedStimulusAuthoring.tpl
> +                                              data-target="body div.qti-item .mainClass .custom-text-box.hashClass "></button>
I don't recommend removing this one. The HTML structure should add a `<p>` for text, so if we keep the `*`, we assure that the descendant, in this case, the `<p>` can have specific rules for the text-colour

2022-09-26 15:00 UTC, Silvia-loza commented on views/js/qtiCreator/component/tpl/sharedStimulusAuthoring.tpl
> +                                              data-target="body div.qti-item .mainClass .custom-text-box.hashClass "></button>
I removed it from here because font color wouldn't apply to all text, see example below... maybe there's another way... 
![image](https://user-images.githubusercontent.com/60346520/192310839-e2b793ce-439e-4b51-97a8-2b3e2b90dacb.png)

2022-09-26 15:46 UTC, marpesia commented on views/js/qtiCreator/component/tpl/sharedStimulusAuthoring.tpl
> +                                              data-target="body div.qti-item .mainClass .custom-text-box.hashClass "></button>
The issue that solves the `*` is to keep the specificity. 
Text Block text color must win over Passage Style Text color, and CSS stylesheet with color rule added to the passage.
This is the AC we should apply.

2022-09-27 08:50 UTC, Silvia-loza commented on views/js/qtiCreator/component/tpl/sharedStimulusAuthoring.tpl
> +                                              data-target="body div.qti-item .mainClass .custom-text-box.hashClass "></button>
Still the color here in both cases is part of the text Block same paragraph, broken by an image, hence we're having the same issue that we had with the background color but with font color in this case. 
Maybe if you don't think this is the right solution maybe we can look at a different approach, but I feel like we should also fix that in the scope of the ticket

2022-09-29 09:30 UTC, bziondik approved these changes
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2022-09-30 06:51 UTC, marpesia approved these changes
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [ ] Pull request's target is not `master`
- [ ] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Commits messages are meaningful
- [ ] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2022-10-04 09:29 UTC, merged