feature: script for moving item assets to given class
oat-sa/extension-tao-mediamanager pull request #485
Opened 2023-10-02 14:28 UTC by Karol-Stelmaczonek

Ticket: https://oat-sa.atlassian.net/browse/PISA25-557

## What's Changed

- Create script for moving item assets to given class

## How to test
Run script in console : php index.php 'oat\taoMediaManager\scripts\MoveResource' [--id] [--namePattern] [--destinationClass]
It can move resource by its id or name pattern, you must specify destination class uri.

Demo:

https://github.com/oat-sa/extension-tao-mediamanager/assets/118974926/d8a8a898-91ba-44e4-8edb-35cb600c20b9

2023-10-03 12:03 UTC, andreluizmachado commented on scripts/MoveResources.php
> +        $mediaInstances = $this->getMediaService()->getRootClass()->getSubClasses(true);
What does it mean the argument true on the getSubClasses?

2023-10-03 12:04 UTC, andreluizmachado commented on scripts/MoveResources.php
> +        $destinationClassId = $this->getOption(self::OPTION_DESTINATION_CLASS_URI);
better to check if the class exists before moving it

2023-10-03 14:50 UTC, Karol-Stelmaczonek commented on scripts/MoveResources.php
> +        $mediaInstances = $this->getMediaService()->getRootClass()->getSubClasses(true);
Its `getSubClasses($recursive = false)` so I want to recursively get all sub classes but, now I don't know its a good idea. Probably we could stick for just first level, not all classes.
https://github.com/oat-sa/generis/blob/b7b6a3bc27afeab2f5e3c1fbc2ef1a96be5be945/core/kernel/classes/class.Class.php#L70

2023-10-03 15:06 UTC, Karol-Stelmaczonek commented on scripts/MoveResources.php
> +        $destinationClassId = $this->getOption(self::OPTION_DESTINATION_CLASS_URI);
Added checking if destination class exists

2023-10-03 15:31 UTC, pnal commented on scripts/MoveResources.php
> +        $mediaInstances = $this->getMediaService()->getRootClass()->getSubClasses(true);
for our purpose to clean up root class we do not need recursive for sure

2023-10-04 07:49 UTC, Karol-Stelmaczonek commented on scripts/MoveResources.php
> +        $mediaInstances = $this->getMediaService()->getRootClass()->getSubClasses(true);
I removed the recursive parameter

2023-10-04 08:56 UTC, pnal requested changes
Good job!
During testing it locally I added dry run mode: https://github.com/oat-sa/extension-tao-mediamanager/pull/487
@Karol-Stelmaczonek let me know if I can merge it

2023-10-04 11:27 UTC, pnal approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [ ] Pull request's target is not `master`
- [ ] Commits are following [conventional commits]
- [ ] Commits messages are meaningful
- [ ] Commits are atomic

2023-10-04 11:30 UTC, pribi approved these changes
LGTM. I see there is no easy way to add DI - so we are still using the legacy version.

2023-10-04 11:36 UTC, pnal commented on scripts/MoveResources.php
> +        return $this->getServiceManager()->getContainer()->get(MediaService::class);
unfortunately we do not support yet DI approach for action class itself, but `MediaService` here is registered in DI container and we getting it using proxy method `->getContainer()`

2023-10-04 13:43 UTC, Karol-Stelmaczonek commented on scripts/MoveResources.php
> +        return $this->getServiceManager()->getContainer()->get(MediaService::class);
I removed usage of getServiceManager()

2023-10-04 13:44 UTC, Karol-Stelmaczonek commented on scripts/MoveResources.php
> +class MoveResources extends ScriptAction
We don't have tests for those script classes and I think adding any would be painfull so I prefer to skip it

2023-10-04 13:44 UTC, merged